=== JetFeng/News-Recommend-System/dom4j-1.6.1/src/conf/repository.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT repository (packagegroup*) >
<!ELEMENT packagegroup ( package* ) >
<!ELEMENT package ( definition |  remotedefinition )  >
<!ELEMENT definition ( info, versionset )  >
<!ELEMENT remotedefinition (#PCDATA) >
<!ELEMENT info ( desc, href ) >
<!ELEMENT desc (#PCDATA) >
<!ELEMENT href (#PCDATA) >
<!ELEMENT versionset ( version* ) >
<!ELEMENT version ( note, jar, dependencies ) >
<!ELEMENT note ( #PCDATA ) >
<!ELEMENT jar ( #PCDATA ) >
<!ELEMENT dependencies ( dep* ) >
<!ELEMENT dep ( #PCDATA ) >

<!ATTLIST packagegroup name  CDATA #REQUIRED >
<!ATTLIST package
        name    CDATA #REQUIRED
        default CDATA #REQUIRED
        latest  CDATA #REQUIRED >
<!ATTLIST version 
        version CDATA #REQUIRED >
<!ATTLIST dep 
        package CDATA #REQUIRED
        version CDATA #REQUIRED >

=== JetFeng/News-Recommend-System/dom4j-1.6.1/src/conf/repository.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE repository SYSTEM "repository.dtd">
<repository>

  <!-- dom4j pakcage group-->

  <packagegroup name="dom4j">

     <!-- JAXP package -->

     <package name="dom4j" latest="1.0" default="1.0">

       <definition>
        <info>
           <desc>dom4j: the flexible XML framework for Java</desc>
           <href>http://dom4j.org</href>
        </info>

        <versionset>
          <version version="1.0">
            <note>production</note>
            <jar>dom4j-1.0.jar</jar>
            <dependencies>
              <dep version="1.1" package="jaxp-parser"/>
            </dependencies>
          </version>

          <version version="1.0-daily">
            <note>current CVS HEAD</note>
            <jar>dom4j-daily.jar</jar>
            <dependencies>
              <dep version="1.1" package="jaxp-parser"/>
            </dependencies>
          </version>
        </versionset>
       </definition>
      </package>
 
  </packagegroup>

</repository>
