=== JetFeng/News-Recommend-System/dom4j-1.6.1/xml/test/schema/test.xsd
<?xml version="1.0" encoding="UTF-8"?><schema xmlns='http://www.w3.org/2001/XMLSchema'> <element name="records">  <complexType>   <sequence>     <element ref="record" minOccurs='1' maxOccurs='unbounded'/>   </sequence>  </complexType> </element> <element name="record">  <complexType>  	<sequence>    	<element name="durationTag" type="duration"/>    	<element name="dateTag" type="date"/>    	<element name="timeTag" type="time"/>    	<element name="dateTimeTag" type="dateTime"/>    	<element name="gYearMonthTag" type="gYearMonth"/>    	<element name="gYearTag" type="gYear"/>    	<element name="gMonthDayTag" type="gMonthDay"/>        <element name="gDayTag" type="gDay"/>    	<element name="gMonthTag" type="gMonth"/>    	<element name="booleanTag" type="boolean"/>    	<element name="base64BinaryTag" type="base64Binary"/>    	<element name="hexBinaryTag" type="hexBinary"/>	    	<element name="floatTag" type="float"/>    	<element name="doubleTag" type="double"/>	    	<element name="decimalTag" type="decimal"/>    	<element name="integerTag" type="integer"/>	    	<element name="nonPositiveIntegerTag" type="nonPositiveInteger"/>    	<element name="negativeIntegerTag" type="negativeInteger"/>	    	<element name="longTag" type="long"/>    	<element name="intTag" type="int"/>    	<element name="shortTag" type="short"/>    	<element name="byteTag" type="byte"/>	    	<element name="nonNegativeIntegerTag" type="nonNegativeInteger"/>    	<element name="unsignedLongTag" type="unsignedLong"/>    	<element name="unsignedIntTag" type="unsignedInt"/>    	<element name="unsignedShortTag" type="unsignedShort"/>    	<element name="unsignedByteTag" type="unsignedByte"/>    	<element name="positiveIntegerTag" type="positiveInteger"/>	</sequence>    <attribute name="id" type="string" />  </complexType>	 </element></schema>

=== JetFeng/News-Recommend-System/dom4j-1.6.1/xml/test/schema/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<records 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation='test.xsd'>

  <record id="foo">
    <durationTag>P1Y2M3DT10H30M</durationTag>
    <dateTag>1999-05-03</dateTag>
    <timeTag>00:00:00</timeTag>
    <dateTimeTag>1999-05-31T13:20:00-05:00</dateTimeTag>
    <gYearMonthTag>1999-05</gYearMonthTag>
    <gYearTag>1999</gYearTag>

    <gMonthDayTag>--12-25</gMonthDayTag>
    <gDayTag>---15</gDayTag>
    <gMonthTag>--10--</gMonthTag>

    <booleanTag>true</booleanTag>
    <base64BinaryTag>cafebabe</base64BinaryTag>
    <hexBinaryTag>cafebabe</hexBinaryTag>
    <floatTag>123.45</floatTag>
    <doubleTag>123.45</doubleTag>

    <decimalTag>123</decimalTag>
    <integerTag>123</integerTag>

    <nonPositiveIntegerTag>-123</nonPositiveIntegerTag>
    <negativeIntegerTag>-123</negativeIntegerTag>

    <longTag>12345678901234</longTag>
    <intTag>12345</intTag>
    <shortTag>1234</shortTag>
    <byteTag>123</byteTag>

    <nonNegativeIntegerTag>123</nonNegativeIntegerTag>
    <unsignedLongTag>123</unsignedLongTag>
    <unsignedIntTag>123</unsignedIntTag>
    <unsignedShortTag>123</unsignedShortTag>
    <unsignedByteTag>123</unsignedByteTag>

    <positiveIntegerTag>123</positiveIntegerTag>

  </record>

</records>
